CREATE TABLE IF NOT EXISTS orders(
  id SERIAL PRIMARY KEY,
  seller_id INT NOT NULL REFERENCES sellers(id) ON DELETE CASCADE ON UPDATE CASCADE,
  client_id INT NOT NULL REFERENCES clients(id) ON DELETE CASCADE ON UPDATE CASCADE,
  status TEXT NOT NULL
);