CREATE TABLE IF NOT EXISTS sellers_categories(
  id SERIAL PRIMARY KEY,
  seller_id INT NOT NULL REFERENCES sellers(id) ON DELETE CASCADE ON UPDATE CASCADE,
  category_id  INT NOT NULL REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE
);